using AutoFixture.Kernel;
using AutoFixture.TUnit.Internal;
using AutoFixture.TUnit.Tests.Internal.DataGeneratorMetadataSupport;
using AutoFixture.TUnit.Tests.TestTypes;

namespace AutoFixture.TUnit.Tests.Internal.DataSources.AutoDataSourceTests;

public class AutoDataSourceTests
{
    [Test]
    public async Task Constructor_WhenCreated_IsDataSource()
    {
        // Arrange & Act
        var sut = new AutoDataSource(() => new DelegatingFixture());

        // Assert
        await Assert.That(sut).IsAssignableTo<IDataSource>();
    }

    [Test]
    public async Task Constructor_WhenCreated_SetsPropertiesToExpectedValues()
    {
        // Arrange
        var fixtureFactory = () => new DelegatingFixture();
        var source = new DelegatingDataSource();

        // Act
        var sut = new AutoDataSource(fixtureFactory, source);

        // Assert
        // Func<T> needs an explicit type arg, or Assert.That invokes it and asserts on IFixture.
        await Assert.That<Func<IFixture>>(sut.CreateFixture).IsSameReferenceAs(fixtureFactory);
        await Assert.That(sut.Source).IsSameReferenceAs(source);
    }

    [Test]
    public async Task GetData_WhenCalled_GeneratesTestDataUsingFixture()
    {
        // Arrange
        var builder = new CompositeSpecimenBuilder(
            new FixedParameterBuilder<string>("a", "value"),
            new FixedParameterBuilder<int>("b", 1),
            new FixedParameterBuilder<double>("c", 12.2));
        var fixture = new DelegatingFixture
        {
            OnCreate = (r, c) => builder.Create(r, c),
        };
        var sut = new AutoDataSource(() => fixture);
        var method = typeof(SampleTestType).GetMethod(nameof(SampleTestType.TestMethodWithMultipleParameters));

        // Act
        var result = sut.GenerateDataSources(DataGeneratorMetadataHelper.CreateDataGeneratorMetadata(method)).Select(x => x()).ToArray();

        // Assert
        await Assert.That(result).IsNotNull();
        await Assert.That(result).HasSingleItem();

        var item = result.Single();
        await Assert.That(item).IsNotNull();
        await Assert.That(item.Length).IsEqualTo(3);
        await Assert.That((string)item[0]).IsEqualTo("value");
        await Assert.That((int)item[1]).IsEqualTo(1);
        await Assert.That((double)item[2]).IsEqualTo(12.2);
    }

    [Test]
    public async Task GetData_WhenSourcePartial_CombinesWithAutoGeneratedValues()
    {
        // Arrange
        var source = new DelegatingDataSource
        {
            TestData =
            [
                ["a", 15],
                ["b", 123],
                ["c", 999]
            ],
        };
        var builder = new FixedParameterBuilder<double>("c", 13.3);
        var fixture = new DelegatingFixture
        {
            OnCreate = (r, c) => builder.Create(r, c),
        };
        var sut = new AutoDataSource(() => fixture, source);
        var method = typeof(SampleTestType)
            .GetMethod(nameof(SampleTestType.TestMethodWithMultipleParameters));

        // Act
        var result = sut.GenerateDataSources(DataGeneratorMetadataHelper.CreateDataGeneratorMetadata(method)).ToArray();

        // Assert
        await Assert.That(result).IsNotNull();
        await Assert.That(result.Length).IsEqualTo(3);
        await Assert.That(result[0]).IsEquivalentTo<object[], object>(["a", 15, 13.3]);
        await Assert.That(result[1]).IsEquivalentTo<object[], object>(["b", 123, 13.3]);
        await Assert.That(result[2]).IsEquivalentTo<object[], object>(["c", 999, 13.3]);
    }

    [Test]
    public async Task GetData_WhenSourceProvidesAllValues_DoesNotGenerateValues()
    {
        // Arrange
        var source = new DelegatingDataSource
        {
            TestData =
            [
                ["a", 85, 913.12],
                ["b", 519, 73.1],
                ["c", 411, 529.6]
            ],
        };
        var fixture = new DelegatingFixture
        {
            OnCreate = (_, _) => throw new InvalidOperationException("Fixture should not be called"),
        };
        var sut = new AutoDataSource(() => fixture, source);
        var method = typeof(SampleTestType)
            .GetMethod(nameof(SampleTestType.TestMethodWithMultipleParameters));

        // Act
        var result = sut.GenerateDataSources(DataGeneratorMetadataHelper.CreateDataGeneratorMetadata(method)).ToArray();

        // Assert
        await Assert.That(result).IsNotNull();
        await Assert.That(result.Length).IsEqualTo(3);
        await Assert.That(result[0]).IsEquivalentTo<object[], object>(["a", 85, 913.12]);
        await Assert.That(result[1]).IsEquivalentTo<object[], object>(["b", 519, 73.1]);
        await Assert.That(result[2]).IsEquivalentTo<object[], object>(["c", 411, 529.6]);
    }

    [Test]
    public async Task GetData_WhenSourceProvidesMoreValuesThanParameters_Throws()
    {
        // Arrange
        var source = new DelegatingDataSource
        {
            TestData = [["a", 1, 2.0, "extra"]],
        };
        var sut = new AutoDataSource(() => new DelegatingFixture(), source);
        var method = typeof(SampleTestType)
            .GetMethod(nameof(SampleTestType.TestMethodWithMultipleParameters));
        var metadata = DataGeneratorMetadataHelper.CreateDataGeneratorMetadata(method);

        // Act & Assert
        await Assert.That(() => sut.GenerateDataSources(metadata).Select(x => x()).ToArray())
            .ThrowsExactly<InvalidOperationException>();
    }

    [Test]
    public async Task GetData_WhenClassDataSourceProvidesMoreValuesThanParameters_Throws()
    {
        // Arrange
        var source = new ClassDataSource(typeof(ClassWithExcessTestData));
        var sut = new AutoDataSource(() => new Fixture(), source);
        var testMethod = typeof(SampleTestType)
            .GetMethod(nameof(SampleTestType.TestMethodWithSingleParameter));
        var metadata = DataGeneratorMetadataHelper.CreateDataGeneratorMetadata(testMethod);

        // Act & Assert
        await Assert.That(async () =>
        {
            await foreach (var rowFunc in sut.GetData(metadata))
            {
                _ = await rowFunc();
            }
        }).ThrowsExactly<InvalidOperationException>();
    }

    [Test]
    public async Task GetData_WhenMemberDataSourceProvidesMoreValuesThanParameters_Throws()
    {
        // Arrange
        var source = new MemberDataSource(
            typeof(AutoDataSourceTests),
            nameof(ExcessMemberData));
        var sut = new AutoDataSource(() => new Fixture(), source);
        var testMethod = typeof(SampleTestType)
            .GetMethod(nameof(SampleTestType.TestMethodWithSingleParameter));
        var metadata = DataGeneratorMetadataHelper.CreateDataGeneratorMetadata(testMethod);

        // Act & Assert
        await Assert.That(async () =>
        {
            await foreach (var rowFunc in sut.GetData(metadata))
            {
                _ = await rowFunc();
            }
        }).ThrowsExactly<InvalidOperationException>();
    }

    [Test]
    public async Task GetData_WhenSourceReturnsNoTestData_ReturnsNoRows()
    {
        // Arrange
        var source = new DelegatingDataSource
        {
            TestData = [],
        };
        var fixture = new DelegatingFixture();
        var sut = new AutoDataSource(() => fixture, source);
        var method = typeof(SampleTestType)
            .GetMethod(nameof(SampleTestType.TestMethodWithMultipleParameters));

        // Act
        var result = sut.GenerateDataSources(DataGeneratorMetadataHelper.CreateDataGeneratorMetadata(method)).ToArray();

        // Assert
        await Assert.That(result).IsEmpty();
    }

    [Test]
    public async Task GetData_WhenSourceReturnsNull_Throws()
    {
        // Arrange
        var source = new DelegatingDataSource { TestData = null };
        var fixture = new DelegatingFixture();
        var sut = new AutoDataSource(() => fixture, source);
        var method = typeof(SampleTestType)
            .GetMethod(nameof(SampleTestType.TestMethodWithMultipleParameters));

        // Act & Assert
        await Assert.That(() => sut.GenerateDataSources(DataGeneratorMetadataHelper.CreateDataGeneratorMetadata(method))
                .ToArray())
            .ThrowsException();
    }

    [Test]
    public async Task GetData_WhenParametersNotCustomized_DoesNotCustomizeFixture()
    {
        // Arrange
        var customizations = new List<ICustomization>();
        var fixture = new DelegatingFixture
        {
            OnCustomize = c => customizations.Add(c)
        };
        var sut = new AutoDataSource(() => fixture);
        var method = typeof(SampleTestType)
            .GetMethod(nameof(SampleTestType.TestMethodWithMultipleParameters));

        // Act
        _ = sut.GenerateDataSources(DataGeneratorMetadataHelper.CreateDataGeneratorMetadata(method)).ToArray();

        // Assert
        await Assert.That(customizations.Count).IsEqualTo(0);
    }

    [Test]
    public async Task GetData_WhenParametersCustomized_CustomizesFixture()
    {
        // Arrange
        var customizations = new List<ICustomization>();
        var fixture = new DelegatingFixture
        {
            OnCustomize = c => customizations.Add(c)
        };
        var sut = new AutoDataSource(() => fixture);
        var method = typeof(SampleTestType)
            .GetMethod(nameof(SampleTestType.TestMethodWithCustomizedParameter));

        // Act
        _ = sut.GenerateDataSources(DataGeneratorMetadataHelper.CreateDataGeneratorMetadata(method)).Select(x => x()).ToArray();

        // Assert
        await Assert.That(customizations.Count).IsGreaterThan(0);
    }

    [Test]
    public async Task GetData_WhenMultipleCustomizations_AppliesInExpectedOrder()
    {
        // Arrange
        var customizations = new List<ICustomization>();
        var fixture = new DelegatingFixture
        {
            OnCustomize = c => customizations.Add(c)
        };
        var sut = new AutoDataSource(() => fixture);
        var method = typeof(SampleTestType)
            .GetMethod(nameof(SampleTestType.TestMethodWithMultipleCustomizations));

        // Act
        _ = sut.GenerateDataSources(DataGeneratorMetadataHelper.CreateDataGeneratorMetadata(method)).Select(x => x()).ToArray();

        // Assert
        using var scope = Assert.Multiple();

        await Assert.That(customizations[0]).IsAssignableTo<FreezeOnMatchCustomization>();
        await Assert.That(customizations[1]).IsAssignableTo<FreezeOnMatchCustomization>();
        await Assert.That(customizations[2]).IsAssignableTo<CompositeCustomization>();
        var composite = (CompositeCustomization)customizations[2];

        var compositeCustomizations = composite.Customizations.ToArray();
        await Assert.That(compositeCustomizations.Length).IsEqualTo(2);
        await Assert.That(compositeCustomizations[0]).IsAssignableTo<ConstructorCustomization>();
        await Assert.That(compositeCustomizations[1]).IsAssignableTo<FreezeOnMatchCustomization>();
    }

    [Test]
    public async Task GetData_WhenSourceYieldsNullRowFactory_Throws()
    {
        // Arrange
        var source = new NullRowFactoryDataSource();
        var sut = new AutoDataSource(() => new DelegatingFixture(), source);
        var method = typeof(SampleTestType)
            .GetMethod(nameof(SampleTestType.TestMethodWithMultipleParameters));
        var metadata = DataGeneratorMetadataHelper.CreateDataGeneratorMetadata(method);

        // Act & Assert
        await Assert.That(async () =>
        {
            await foreach (var rowFunc in sut.GetData(metadata))
            {
                _ = await rowFunc();
            }
        }).ThrowsExactly<InvalidOperationException>();
    }

    public static IEnumerable<object[]> ExcessMemberData()
    {
        yield return ["one", "two", "three"];
    }

    private sealed class NullRowFactoryDataSource : BaseDataSourceAttribute
    {
#pragma warning disable CS1998
        public override async IAsyncEnumerable<Func<Task<object?[]?>>> GetData(
            DataGeneratorMetadata dataGeneratorMetadata)
        {
            yield return null!;
        }
#pragma warning restore CS1998
    }
}
